const crypto=require('crypto');
const hash=v=>crypto.createHash('sha256').update(String(v||'')).digest('hex');
const newJobId=()=>`job_${Date.now().toString(36)}_${crypto.randomBytes(6).toString('hex')}`;
const isJobId=s=>/^job_[0-9a-z]+_[0-9a-f]+$/.test(String(s||''));
function okPass(headers,body,env){if(!env.APP_PASSCODE)return true;return String(headers.get('x-app-passcode')||body?.passcode||'')===String(env.APP_PASSCODE)}
async function enc(v,env){const secret=String(env.JOB_SECRET||'');if(!secret)return{encrypted:false,value:v};const raw=crypto.createHash('sha256').update(secret).digest();const key=await crypto.webcrypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt']);const iv=crypto.randomBytes(12);const out=Buffer.from(await crypto.webcrypto.subtle.encrypt({name:'AES-GCM',iv},key,Buffer.from(String(v))));const tag=out.subarray(-16),data=out.subarray(0,-16);return{encrypted:true,value:`${iv.toString('base64url')}.${tag.toString('base64url')}.${data.toString('base64url')}`}}
async function createJob({store,env,headers,bodyText,jobId}){let body;try{body=JSON.parse(bodyText||'{}')}catch{return{status:400,body:{error:'JSON không hợp lệ'}}}if(!okPass(headers,body,env))return{status:401,body:{error:'Sai APP_PASSCODE'}};const storyState=body.storyState;if(!storyState)return{status:400,body:{error:'Thiếu storyState'}};const apiKey=String(body.apiKey||env.OPENROUTER_API_KEY||'').replace(/^Bearer\s+/i,'').trim();if(!apiKey)return{status:401,body:{error:'Thiếu OpenRouter API key'}};if(JSON.stringify(storyState).length>8000000)return{status:413,body:{error:'Story state quá lớn'}};const accessToken=crypto.randomBytes(32).toString('base64url');const now=Date.now();const primaryModel=String(body.primaryModel||body.xuongPrimaryModel||'').trim();const nsfwModel=String(body.modelNsfw||body.nsfwModel||'').trim();const suppliedSecondary=String(body.secondaryModel||body.xuongSecondaryModel||'').trim();const secondaryModel=suppliedSecondary||nsfwModel;const modelMode=String(body.modelMode||body.xuongModelMode||'none').toLowerCase();const job={schemaVersion:16,jobId,storyId:storyState.storyId||null,baseChapterCount:Array.isArray(storyState.chapters)?storyState.chapters.length:0,status:'pending',createdAt:now,updatedAt:now,apiEndpoint:body.apiEndpoint||'https://openrouter.ai/api/v1/chat/completions',model:body.model||env.DEFAULT_MODEL||'deepseek/deepseek-v3.2',primaryModel,secondaryModel,modelNsfw:nsfwModel,modelMode,forceNsfw:!!body.forceNsfw,apiKeyEncrypted:await enc(apiKey,env),accessTokenHash:hash(accessToken),storyState,resultChapter:null,error:null,progress:'Đang chờ bắt đầu...'};await store.setJSON(jobId,job);return{status:200,body:{success:true,jobId,accessToken,message:'Job đã tạo; Durable Object sẽ tự chạy nền.'}}}
async function jobStatus({store,jobId,token,ack}){const job=await store.get(jobId);if(!job)return{status:404,body:{error:'Job not found'}};if(job.accessTokenHash!==hash(token))return{status:403,body:{error:'Token không hợp lệ'}};if(ack==='1'&&(job.status==='completed'||job.status==='failed')){await store.delete();return{status:200,body:{deleted:true,jobId}}}const safe={schemaVersion:job.schemaVersion,jobId:job.jobId,storyId:job.storyId,status:job.status,progress:job.progress,createdAt:job.createdAt,updatedAt:job.updatedAt,completedAt:job.completedAt||null,error:job.error||null,resultChapter:job.resultChapter||null,newChapterCount:job.storyState?.chapters?.length||0,modelMode:job.modelMode||'none',activeModel:job.activeModel||job.model||null,nsfwModel:job.modelNsfw||job.secondaryModel||null};if(job.status==='completed')safe.storyState=job.storyState;return{status:200,body:safe}}
module.exports={newJobId,isJobId,createJob,jobStatus};
