import api from './api.cjs';
export { JobDO } from './job-do.mjs';
const cors=(env)=>({'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-App-Passcode, X-Model-Mode, X-Primary-Model, X-Secondary-Model, X-NSFW-Model','Cache-Control':'no-store'});
const json=(env,status,obj)=>new Response(status===204?null:JSON.stringify(obj),{status,headers:{'Content-Type':'application/json',...cors(env)}});
const relay=(env,res)=>{const h=new Headers(res.headers);Object.entries(cors(env)).forEach(([k,v])=>h.set(k,v));return new Response(res.body,{status:res.status,headers:h})};
const stub=(env,id)=>env.JOBS.get(env.JOBS.idFromName(id));
function messageText(body){return(Array.isArray(body?.messages)?body.messages:[]).map(m=>typeof m?.content==='string'?m.content:'').join('\n')}
function isLongChapterRequest(body){const text=messageText(body).toLowerCase();return /chương\s+\d+/.test(text)&&/(\d[,.]?\d*)\s*từ/.test(text)&&/(viết|nội dung chương|tiểu thuyết)/.test(text)}
function extractTarget(body){const text=messageText(body);const m=text.match(/(?:mục tiêu|khoảng|ít nhất|tối thiểu)\s*(\d[\d,.]*)\s*từ/i)||text.match(/(\d[\d,.]*)\s*từ/i);const n=m?Number(String(m[1]).replace(/[,.]/g,'')):5000;return Math.min(Math.max(n||5000,2500),7000)}
function contentOf(data){const c=data?.choices?.[0]?.message?.content;return typeof c==='string'?c:Array.isArray(c)?c.map(x=>typeof x==='string'?x:x?.text||'').join(''):''}
function wordCount(t){return String(t||'').trim().split(/\s+/).filter(Boolean).length}
function normalizeAiBody(body,request){if(!body||typeof body!=='object')return body;const out={...body};const hdr=(n)=>String(request?.headers?.get(n)||'').trim();const mode=String(out.xuongModelMode||hdr('X-Model-Mode')||'').toLowerCase();const primary=String(out.xuongPrimaryModel||hdr('X-Primary-Model')||'').trim();const nsfw=String(out.modelNsfw||out.nsfwModel||out.xuongNsfwModel||hdr('X-NSFW-Model')||'').trim();const secondary=String(out.xuongSecondaryModel||hdr('X-Secondary-Model')||nsfw).trim();const forceNsfw=!!(out.forceNsfw||out.nsfw||out.isNsfw||out.matureFocus==='secondary'||out.matureFocus==='nsfw');if(forceNsfw&&secondary)out.model=secondary;else if(mode==='primary'&&primary)out.model=primary;else if(mode==='secondary'&&secondary)out.model=secondary;else if(mode==='auto'&&primary)out.model=primary;if(isLongChapterRequest(out)){const requested=Number(out.max_tokens)||0;if(requested<10000)out.max_tokens=10000;}delete out.xuongModelMode;delete out.xuongPrimaryModel;delete out.xuongSecondaryModel;delete out.xuongNsfwModel;return out}
async function openRouterOnce(body,env,request,url){const key=String(env.OPENROUTER_API_KEY||'').trim()||(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!key)return new Response(JSON.stringify({error:'Chưa cấu hình OpenRouter API key'}),{status:401,headers:{'Content-Type':'application/json'}});const headers={'content-type':'application/json',authorization:'Bearer '+key,'http-referer':url.origin,'x-title':'Xuong Truyen AI'};return fetch(body.apiEndpoint||'https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers,body:JSON.stringify(normalizeAiBody(body,request))})}
async function openRouter(body,env,request,url){const mode=String(body?.xuongModelMode||request.headers.get('X-Model-Mode')||'').toLowerCase();const nsfw=String(body?.modelNsfw||body?.nsfwModel||body?.xuongNsfwModel||request.headers.get('X-NSFW-Model')||'').trim();const secondary=String(body?.xuongSecondaryModel||request.headers.get('X-Secondary-Model')||nsfw).trim();const forceNsfw=!!(body?.forceNsfw||body?.nsfw||body?.isNsfw||body?.matureFocus==='secondary'||body?.matureFocus==='nsfw');const first=await openRouterOnce(body,env,request,url);if(forceNsfw&&secondary&&first.ok)return first;if(mode!=='auto'||!secondary||first.ok)return first;if(first.status!==408&&first.status!==409&&first.status!==425&&first.status!==429&&first.status<500)return first;const retry={...body,xuongModelMode:'secondary',xuongSecondaryModel:secondary,model:secondary};return openRouterOnce(retry,env,request,url)}
async function runLongChapter(body,env,request,url){const target=extractTarget(body);const maxRounds=5;let accumulated='';let lastResponse=null;let modelUsed=normalizeAiBody(body,request)?.model||body.model;for(let i=0;i<maxRounds&&wordCount(accumulated)<Math.floor(target*.8);i++){const baseMessages=Array.isArray(body.messages)?body.messages:[];const prompt=i===0?baseMessages:[...baseMessages,{role:'user',content:`Đây là phần văn bản đã viết của cùng chương:\n<da_viet>\n${accumulated.slice(-22000)}\n</da_viet>\nHãy viết TIẾP ngay từ đoạn cuối, không lặp lại, không tóm tắt, không kết thúc sớm. Thêm khoảng 1000-1600 từ tiếng Việt và giữ nguyên nhân vật, bối cảnh, canon, giọng văn. Chỉ trả phần văn xuôi mới.`}];const partBody={...body,messages:prompt,max_tokens:10000};const res=await openRouter(partBody,env,request,url);lastResponse=res;if(!res.ok)break;const data=await res.clone().json().catch(()=>null);const part=contentOf(data);if(!part.trim())break;accumulated=accumulated?accumulated+'\n\n'+part:part;modelUsed=data?.model||modelUsed}
if(!lastResponse)return new Response(JSON.stringify({error:'Không nhận được phản hồi model'}),{status:502,headers:{'Content-Type':'application/json'}});if(!accumulated)return lastResponse;const out={choices:[{index:0,message:{role:'assistant',content:accumulated},finish_reason:'stop'}],model:modelUsed,object:'chat.completion',x_truyen_ai:{longChapter:true,wordCount:wordCount(accumulated),target}};return new Response(JSON.stringify(out),{status:200,headers:{'Content-Type':'application/json'}})}
async function serveApp(request,env){const res=await env.ASSETS.fetch(request);const ct=res.headers.get('content-type')||'';if(!ct.includes('text/html'))return res;let html=await res.text();html=html.replace(/\/.netlify\/functions/gi,'/api/bg');if(!html.includes('/hot-switch.js'))html=html.replace(/<\/body>/i,'<script src="/hot-switch.js" defer></script></body>');const headers=new Headers(res.headers);headers.delete('content-length');headers.set('content-type','text/html; charset=UTF-8');return new Response(html,{status:res.status,statusText:res.statusText,headers})}
export default {async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return json(env,204,{});if(!u.pathname.startsWith('/api/'))return serveApp(request,env);if(!env.JOBS)return json(env,500,{error:'Durable Object JOBS chưa được bind'});const route=u.pathname.slice(5).replace(/\/+$/,'');if(route==='health')return json(env,200,{ok:true,service:'truyen-ai',architecture:'single-worker+durable-object+openrouter',durableObject:!!env.JOBS,openRouterConfigured:!!String(env.OPENROUTER_API_KEY||'').trim(),time:new Date().toISOString()});if(route==='ai'){if(request.method!=='POST')return json(env,405,{error:'Method not allowed'});let body;try{body=await request.json()}catch{return json(env,400,{error:'JSON không hợp lệ'})}if(!body?.model||!Array.isArray(body?.messages))return json(env,400,{error:'Thiếu model hoặc messages'});if(isLongChapterRequest(body))return runLongChapter(body,env,request,u);const up=await openRouter(body,env,request,u);return relay(env,up)}if(route==='create-job'||route==='bg/create-job'){if(request.method!=='POST')return json(env,405,{error:'Method not allowed'});const id=api.newJobId();const h=new Headers({'content-type':'application/json','x-job-id':id});const pc=request.headers.get('x-app-passcode');if(pc)h.set('x-app-passcode',pc);const res=await stub(env,id).fetch('https://job/init',{method:'POST',headers:h,body:request.body});return relay(env,res)}if(route==='job-status'||route==='bg/job-status'){if(request.method!=='GET')return json(env,405,{error:'Method not allowed'});const id=u.searchParams.get('jobId');if(!api.isJobId(id))return json(env,404,{error:'Job not found'});const h=new Headers();const au=request.headers.get('authorization');if(au)h.set('authorization',au);return relay(env,await stub(env,id).fetch('https://job/status'+u.search,{headers:h}))}return json(env,404,{error:'API route not found'})}};
