import api from './api.cjs';
export { JobDO } from './job-do.mjs';
const cors=(env)=>({'Access-Control-Allow-Origin':env.ALLOWED_ORIGIN||'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-App-Passcode','Cache-Control':'no-store'});
const json=(env,status,obj)=>new Response(status===204?null:JSON.stringify(obj),{status,headers:{'Content-Type':'application/json',...cors(env)}});
const relay=(env,res)=>{const h=new Headers(res.headers);Object.entries(cors(env)).forEach(([k,v])=>h.set(k,v));return new Response(res.body,{status:res.status,headers:h})};
const stub=(env,id)=>env.JOBS.get(env.JOBS.idFromName(id));
function isLongChapterRequest(body){const text=(Array.isArray(body?.messages)?body.messages:[]).map(m=>typeof m?.content==='string'?m.content:'').join('\n').toLowerCase();return /chương\s+\d+/.test(text)&&/(\d[,.]?\d*)\s*từ/.test(text)&&/(viết|nội dung chương|tiểu thuyết)/.test(text)}
function normalizeAiBody(body){if(!isLongChapterRequest(body))return body;const out={...body};const requested=Number(out.max_tokens)||0;if(requested<10000)out.max_tokens=10000;return out}
export default {async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return json(env,204,{});if(!u.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);if(!env.JOBS)return json(env,500,{error:'Durable Object JOBS chưa được bind'});const route=u.pathname.slice(5).replace(/\/+$/,'');if(route==='ai'){if(request.method!=='POST')return json(env,405,{error:'Method not allowed'});let body;try{body=await request.json()}catch{return json(env,400,{error:'JSON không hợp lệ'})}if(!body?.model||!Array.isArray(body?.messages))return json(env,400,{error:'Thiếu model hoặc messages'});const key=String(env.OPENROUTER_API_KEY||'').trim()||(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');if(!key)return json(env,401,{error:'Chưa cấu hình OpenRouter API key'});const headers={'content-type':'application/json',authorization:'Bearer '+key,'http-referer':u.origin,'x-title':'Xuong Truyen AI'};const up=await fetch(body.apiEndpoint||'https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers,body:JSON.stringify(normalizeAiBody(body))});return relay(env,up)}if(route==='create-job'||route==='bg/create-job'){if(request.method!=='POST')return json(env,405,{error:'Method not allowed'});const id=api.newJobId();const h=new Headers({'content-type':'application/json','x-job-id':id});const pc=request.headers.get('x-app-passcode');if(pc)h.set('x-app-passcode',pc);const res=await stub(env,id).fetch('https://job/init',{method:'POST',headers:h,body:request.body});return relay(env,res)}if(route==='job-status'||route==='bg/job-status'){if(request.method!=='GET')return json(env,405,{error:'Method not allowed'});const id=u.searchParams.get('jobId');if(!api.isJobId(id))return json(env,404,{error:'Job not found'});const h=new Headers();const au=request.headers.get('authorization');if(au)h.set('authorization',au);return relay(env,await stub(env,id).fetch('https://job/status'+u.search,{headers:h}))}return json(env,404,{error:'API route not found'})}};
