const crypto=require('crypto');
const DEFAULT_ENDPOINT='https://openrouter.ai/api/v1/chat/completions';
let ENV={};
const ev=n=>(ENV&&ENV[n])||'';
const words=t=>String(t||'').trim().split(/\s+/).filter(Boolean).length;
function limits(st){const target=Math.min(Math.max(Number(st?.minChapterWords)||5000,500),7000);return{target,hardMax:Math.ceil(target*1.15)}}
function trim(t,max){const s=String(t||'').trim();if(words(s)<=max)return s;const r=/\S+/g;let m,n=0,e=0;while((m=r.exec(s))){n++;e=m.index+m[0].length;if(n>=max)break}let o=s.slice(0,e),k=Math.max(o.lastIndexOf('. '),o.lastIndexOf('! '),o.lastIndexOf('? '),o.lastIndexOf('… '));if(k>o.length*.75)o=o.slice(0,k+1);return o.trim()}
function clean(t){return String(t||'').replace(/<think(?:ing)?[\s>][\s\S]*?<\/think(?:ing)?>/gi,'').replace(/[\u3400-\u4DBF\u4E00-\u9FFF\u3040-\u30FF\uAC00-\uD7AF\u0400-\u04FF\u0E00-\u0E7F\u0600-\u06FF\u0900-\u097F]+/g,'').replace(/\r\n?/g,'\n').trim()}
function paras(t){return String(t||'').replace(/\r\n?/g,'\n').trim().split(/\n{2,}/).map(x=>x.trim()).filter(Boolean).join('\n\n')}
function content(d){const c=d?.choices?.[0]?.message?.content;return typeof c==='string'?c:Array.isArray(c)?c.map(x=>typeof x==='string'?x:x?.text||'').join(''):''}
async function decrypt(rec){if(!rec)return'';if(!rec.encrypted)return rec.value||'';const secret=ev('JOB_SECRET');if(!secret)throw Error('Thiếu JOB_SECRET để giải mã API key.');const raw=crypto.createHash('sha256').update(secret).digest();const [iv,tag,data]=String(rec.value).split('.');const key=await crypto.webcrypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['decrypt']);const plain=await crypto.webcrypto.subtle.decrypt({name:'AES-GCM',iv:Buffer.from(iv,'base64url')},key,Buffer.concat([Buffer.from(data,'base64url'),Buffer.from(tag,'base64url')]));return Buffer.from(plain).toString()}
async function ask(endpoint,key,model,messages,max_tokens=9000,temp=.7){if(!model)throw Error('Chưa chọn model');const r=await fetch(endpoint||DEFAULT_ENDPOINT,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+key,'http-referer':'https://xuong-truyen-ai','x-title':'Xuong Truyen AI'},body:JSON.stringify({model,messages,temperature:temp,max_tokens,stream:false})});const tx=await r.text();let d;try{d=JSON.parse(tx)}catch{throw Error('OpenRouter trả về dữ liệu không hợp lệ')};if(!r.ok)throw Error(d?.error?.message||'OpenRouter HTTP '+r.status);const out=content(d);if(!out.trim())throw Error('OpenRouter trả về nội dung rỗng');return out}
function modelPlan(job){const base=job.model||envDefault()||'deepseek/deepseek-v3.2',p=String(job.primaryModel||'').trim(),s=String(job.secondaryModel||'').trim(),mode=String(job.modelMode||'none').toLowerCase();if(mode==='secondary'&&s)return{active:s,fallback:null};if((mode==='primary'||mode==='auto')&&p)return{active:p,fallback:mode==='auto'&&s&&s!==p?s:null};if(mode==='auto'&&s&&s!==base)return{active:base,fallback:s};return{active:base,fallback:null}}
function envDefault(){return String(ENV.DEFAULT_MODEL||'')}
function context(st){return JSON.stringify({storyTitle:st?.storyTitle||st?.title||'',chapterNumber:(st?.chapters?.length||0)+1,styleBible:st?.styleBible||st?.style||'',storyBible:st?.storyBible||'',worldRules:st?.worldRules||'',lorebook:st?.lorebook||'',currentStatus:st?.currentStatus||st?.currentState||'',characters:Array.isArray(st?.characters)?st.characters.slice(0,80):[],locations:Array.isArray(st?.locations)?st.locations.slice(0,50):[],items:Array.isArray(st?.items)?st.items.slice(0,50):[],threads:Array.isArray(st?.threads)?st.threads.slice(0,50):[],recentChapters:Array.isArray(st?.chapters)?st.chapters.slice(-3).map(c=>({number:c.number,title:c.title,summary:c.summary||'',content:String(c.content||'').slice(-12000)})):[]})}
function chapterPrompt(st){const n=(st?.chapters?.length||0)+1,l=limits(st);return `Viết CHƯƠNG ${n} tiểu thuyết hoàn chỉnh bằng tiếng Việt dựa CHỈ trên dữ liệu truyện bên dưới. Mục tiêu tổng cộng khoảng ${l.target} từ. Chỉ 1-3 sự kiện chính. Không tự mở nhiều tuyến truyện mới, không tự tạo nhân vật quan trọng mới, không phá quan hệ/canon. Viết văn xuôi có hành động, nội tâm và đối thoại; mỗi đoạn cách một dòng trống, mỗi lượt thoại là đoạn riêng. Không viết phân tích, outline, Draft hay tiếng Anh. Nếu có nextChapterHint thì ưu tiên nhưng không phá canon. Đây là PHẦN 1 của quy trình nhiều lượt: hãy viết một phần lớn, khoảng 1400-1900 từ, và dừng ở một điểm tự nhiên để lượt sau nối tiếp.\n<story>${context(st)}</story>\nChỉ trả nội dung chương, bắt đầu ngay bằng văn xuôi.`}
function continuationPrompt(st,current,partNo){const n=(st?.chapters?.length||0)+1,l=limits(st),tail=String(current||'').slice(-18000);return `Bạn đang tiếp tục CHƯƠNG ${n}, lượt ${partNo}. Chương hiện có ${words(current)} từ và mục tiêu tổng cộng khoảng ${l.target} từ. Hãy VIẾT TIẾP ngay từ đoạn cuối, thêm khoảng 1000-1600 từ tiếng Việt. Không lặp lại câu, đoạn, sự kiện hoặc đối thoại đã có. Không mở tuyến truyện mới ngoài 1-3 sự kiện chính. Giữ nguyên nhân vật, quan hệ, địa điểm, vật phẩm và canon. Không tóm tắt phần trước, không nói "tiếp tục", không outline, không tiếng Anh. Mỗi đoạn cách một dòng trống, mỗi lượt thoại là đoạn riêng. Nếu còn thiếu mục tiêu, phải tiếp tục phát triển sự kiện hiện tại thay vì kết thúc sớm.\n<story>${context(st)}</story>\n<last_part>${tail}</last_part>\nChỉ trả phần văn xuôi mới nối tiếp.`}
function metaPrompt(st,ch){const n=(st?.chapters?.length||0)+1;return `Trả JSON thuần cho CHƯƠNG ${n}. Chỉ dựa vào dữ liệu hiện tại và chương. Schema: {"summary":"300-400 từ","currentStatus":"trạng thái cuối chương","characterUpdates":[{"name":"","state":""}],"worldUpdates":[{"name":"","state":""}],"foreshadowing":[""],"knowledgeLedger":[""],"nextChapterHint":"400-600 từ, cụ thể"}. Không thêm nhân vật không xuất hiện. Nếu không đổi dùng [] hoặc ''. Dữ liệu hiện tại: ${context(st)}\nCHƯƠNG: ${ch}`}
function parse(s){const x=String(s||'').replace(/^```json\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(x)}catch{const a=x.indexOf('{'),b=x.lastIndexOf('}');if(a>=0&&b>a)try{return JSON.parse(x.slice(a,b+1))}catch{}return null}}
function merge(st,ch,m,n){const s=JSON.parse(JSON.stringify(st||{}));s.chapters=Array.isArray(s.chapters)?s.chapters:[];ch.number=n;ch.wordCount=words(ch.content);ch.summary=m?.summary||'';s.chapters.push(ch);if(m?.currentStatus)s.currentStatus=m.currentStatus;if(Array.isArray(m?.foreshadowing))s.foreshadowing=m.foreshadowing;if(Array.isArray(m?.knowledgeLedger))s.knowledgeLedger=m.knowledgeLedger;if(m?.nextChapterHint)s.nextChapterHint=m.nextChapterHint;if(Array.isArray(s.characters)&&Array.isArray(m?.characterUpdates))for(const u of m.characterUpdates){const c=s.characters.find(x=>String(x?.name||'').trim()===String(u?.name||'').trim());if(c&&u.state)c.currentState=u.state}return s}
async function askWithFallback(endpoint,key,plan,messages,maxTokens,temp,onProgress){try{return{model:plan.active,text:await ask(endpoint,key,plan.active,messages,maxTokens,temp)}}catch(e){if(!plan.fallback||plan.fallback===plan.active)throw e;await onProgress?.(`PRIMARY lỗi — chuyển nóng sang SECONDARY: ${plan.fallback}`);return{model:plan.fallback,text:await ask(endpoint,key,plan.fallback,messages,maxTokens,temp)}}}
async function generateChapter(job,key,plan,endpoint,st,onProgress){const n=(st?.chapters?.length||0)+1,l=limits(st),sys='Bạn là nhà văn tiểu thuyết tiếng Việt, ưu tiên continuity và văn phong tự nhiên.';let model=plan.active,text='',partNo=0;const maxParts=8;while(words(text)<l.target&&partNo<maxParts){partNo++;const isFirst=partNo===1,prompt=isFirst?chapterPrompt(st):continuationPrompt(st,text,partNo),minAccept=isFirst?900:650,maxTokens=isFirst?10000:9000;await onProgress?.(`Đang viết ${isFirst?'phần đầu':'phần tiếp '+partNo+'/'+maxParts} · ${model} · ${words(text)}/${l.target} từ`);let result=await askWithFallback(endpoint,key,{active:model,fallback:plan.fallback},[{role:'system',content:sys},{role:'user',content:prompt}],maxTokens,isFirst ? .72 : .68,onProgress);let part=paras(clean(result.text)),got=words(part);model=result.model;if(got<minAccept){const retryPrompt=prompt+`\n\nQUAN TRỌNG: Output trước quá ngắn. Lượt này BẮT BUỘC phải tạo ít nhất ${minAccept} từ, không được kết thúc sớm. Hãy viết tiếp diễn biến thay vì tóm tắt.`;await onProgress?.(`Output ngắn (${got} từ) — yêu cầu model viết lại lượt ${partNo}`);const retry=await askWithFallback(endpoint,key,{active:model,fallback:plan.fallback},[{role:'system',content:sys},{role:'user',content:retryPrompt}],maxTokens,.64,onProgress);part=paras(clean(retry.text));got=words(part);model=retry.model}if(got<400)throw Error(`Model trả phần quá ngắn (${got} từ) ở lượt ${partNo}; không đủ để hoàn thành chương.`);text=text?paras(text+'\n\n'+part):part;await onProgress?.(`Đã có ${words(text)}/${l.target} từ`)}if(words(text)<Math.floor(l.target*.8))throw Error(`Chương sinh ra quá ngắn: ${words(text)} từ / mục tiêu ${l.target} từ`);return{model,text:trim(text,l.hardMax)}}
async function runJob(store,jobId,env){ENV=env||{};let job=await store.get(jobId);if(!job)throw Error('Job không tồn tại');if(job.status==='completed')return{statusCode:200};job.status='running';job.progress='Đang chuẩn bị dữ liệu truyện...';job.updatedAt=Date.now();await store.setJSON(jobId,job);try{const key=await decrypt(job.apiKeyEncrypted)||String(env.OPENROUTER_API_KEY||'');if(!key)throw Error('Chưa cấu hình OPENROUTER_API_KEY và job không có API key');const endpoint=job.apiEndpoint||DEFAULT_ENDPOINT,n=(job.storyState?.chapters?.length||0)+1,plan=modelPlan(job);job.activeModel=plan.active;await store.setJSON(jobId,job);const result=await generateChapter(job,key,plan,endpoint,job.storyState,async p=>{job.progress=p;job.updatedAt=Date.now();await store.setJSON(jobId,job)});const model=result.model,text=result.text,lim=limits(job.storyState);if(words(text)<Math.floor(lim.target*.8))throw Error(`Chương chưa đạt 80% mục tiêu: ${words(text)} từ`);const chapter={title:'Chương '+n,content:text,wordCount:words(text)};job.activeModel=model;job.progress='Đang cập nhật Summary, Character State, Current Status, Memory...';await store.setJSON(jobId,job);let metaResult;try{metaResult=await askWithFallback(endpoint,key,{active:model,fallback:plan.fallback},[{role:'system',content:'Bạn là bộ máy continuity. Chỉ trả JSON hợp lệ.'},{role:'user',content:metaPrompt(job.storyState,text)}],3000,.2,async p=>{job.progress=p;job.updatedAt=Date.now();await store.setJSON(jobId,job)})}catch(e){metaResult={model,text:'{}'};job.progress='Không tạo được metadata, giữ nguyên chương và hoàn tất an toàn.';await store.setJSON(jobId,job)}const m=parse(metaResult.text)||{};job.storyState=merge(job.storyState,chapter,m,n);job.resultChapter=chapter;job.status='completed';job.progress=`Hoàn thành · ${chapter.wordCount} từ`;job.updatedAt=Date.now();job.completedAt=Date.now();job.apiKey=null;job.apiKeyEncrypted=null;await store.setJSON(jobId,job);return{statusCode:200,body:JSON.stringify({success:true,jobId,wordCount:chapter.wordCount,activeModel:model,modelMode:job.modelMode||'none'})}}catch(e){job.status='failed';job.error=e?.message||String(e);job.progress='Lỗi: '+job.error;job.updatedAt=Date.now();job.apiKey=null;job.apiKeyEncrypted=null;await store.setJSON(jobId,job);return{statusCode:500,body:JSON.stringify({error:job.error,jobId})}}}
module.exports={runJob};
