import crypto from "node:crypto";
const DEFAULT_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions";
const TTL = 172800;
const json = (o,s=200) => new Response(JSON.stringify(o),{status:s,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-methods":"POST,OPTIONS","access-control-allow-headers":"Content-Type,X-App-Passcode"}});
const hash=v=>crypto.createHash("sha256").update(String(v||"")).digest("hex");
const tok=()=>crypto.randomBytes(32).toString("base64url");
function encryptApiKey(apiKey,secret){if(!secret)return {encrypted:false,value:apiKey};const key=crypto.createHash("sha256").update(secret).digest();const iv=crypto.randomBytes(12);const c=crypto.createCipheriv("aes-256-gcm",key,iv);const enc=Buffer.concat([c.update(apiKey,"utf8"),c.final()]);return {encrypted:true,value:`${iv.toString("base64url")}.${c.getAuthTag().toString("base64url")}.${enc.toString("base64url")}`};}
function passOK(r,e,b){const p=String(e.APP_PASSCODE||"");return !p || (r.headers.get("X-App-Passcode")||String(b?.appPasscode||""))===p;}
function endpoint(raw){try{const u=new URL(raw||DEFAULT_ENDPOINT);if(!/^https?:$/.test(u.protocol))return {ok:false,error:"Endpoint phải dùng http/https"};return {ok:true,url:u.toString()};}catch{return {ok:false,error:"Endpoint không hợp lệ"};}}
export async function onRequest(context){if(context.request.method==="OPTIONS")return json({},204);if(context.request.method!=="POST")return json({error:"Method not allowed"},405);let b={};try{b=await context.request.json();}catch{return json({error:"JSON không hợp lệ"},400);}const {request,env}=context;if(!passOK(request,env,b))return json({error:"Sai hoặc thiếu mã truy cập (APP_PASSCODE).",needPasscode:true},401);const storyState=b.storyState;const apiKey=String(b.apiKey||"").trim().replace(/^bearer\s+/i,"").replace(/^["']|["']$/g,"");if(!storyState||!apiKey)return json({error:"Thiếu storyState hoặc API key"},400);const ep=endpoint(b.apiEndpoint);if(!ep.ok)return json({error:ep.error},400);if(JSON.stringify(storyState).length>8000000)return json({error:"Story state quá lớn."},413);const jobId="job_"+Date.now().toString(36)+"_"+crypto.randomBytes(6).toString("hex");const accessToken=tok();const workerToken=tok();const now=Date.now();const job={schemaVersion:10.2,jobId,storyId:storyState.storyId||null,baseChapterCount:Array.isArray(storyState.chapters)?storyState.chapters.length:0,status:"pending",createdAt:now,updatedAt:now,apiEndpoint:ep.url,model:b.model||"deepseek/deepseek-v3.2",modelNsfw:b.modelNsfw||"aion-labs/aion-2.0",forceNsfw:!!b.forceNsfw,hintStyle:String(b.hintStyle||"normal").slice(0,20),hintFormat:String(b.hintFormat||"detail").slice(0,20),apiKeyEncrypted:encryptApiKey(apiKey,String(env.JOB_SECRET||"")),apiKey:null,accessTokenHash:hash(accessToken),workerTokenHash:hash(workerToken),storyState,resultChapter:null,error:null,progress:"Đang chờ bắt đầu..."};await env.STORY_JOBS.put(jobId,JSON.stringify(job),{expirationTtl:TTL});await env.BACKGROUND_QUEUE.send({jobId,workerToken});return json({success:true,jobId,accessToken,warnings:env.JOB_SECRET?[]:["JOB_SECRET chưa được cấu hình; API key được lưu tạm dạng không mã hóa trong job KV."],message:"Job đã được tạo. Có thể đóng/tắt iPhone; khi mở lại app sẽ tự kiểm tra và đồng bộ."});}
